@startuml
title Standart Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(cc_mngr, "Call-center manager")
Person(pcc_mngr, "Partner Call-center manager")


System(abc, "АБС")
System(cc_system, "Сервис call-center")
System_Ext(pcc_system, "Сервис call-center партнера")

Rel(cc_mngr, cc_system, "Просмотр акутальных ставок")
Rel(pcc_mngr, pcc_system, "Просмотр акутальных ставок")

Rel(cc_system, pcc_system, "Загрузка ставко на smtp-сервер")
Rel(abc, cc_system, "Оповещение об изменении ставки")

@enduml
